name: "goast"
description: "Runs goast as GitHub action for customizable static analysis of Go code"
inputs:
  policy:
    description: "Rego policy file or directory"
    required: true
  format:
    description: "Output format [text|json]"
    default: "text"
  output:
    description: "Output destination"
    default: "-"
  source:
    description: "Source code files or directory"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - eval
    - --policy="${{ inputs.policy }}"
    - --format="${{ inputs.format }}"
    - --output="${{ inputs.output }}"
    - ${{ inputs.source }}
